# Generated by Django 5.2.6 on 2025-09-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('developer', 'Developer'), ('tester', 'Tester')], max_length=20)),
                ('experience_years', models.IntegerField()),
                ('skills', models.TextField()),
                ('join_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
