# Generated by Django 5.2.6 on 2025-09-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('tasks', '0003_remove_task_assigned_to_task_assigned_to'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserSanay',
        ),
    ]
